'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.296
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.296.
'
Namespace WebReference
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="UBSWebserviceSoapBinding", [Namespace]:="http://www.openuri.org/")>  _
    Partial Public Class UBSWebservice
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private getBackEndStoredProcedureCallOperationCompleted As System.Threading.SendOrPostCallback
        
        Private adaptorServiceOperationCompleted As System.Threading.SendOrPostCallback
        
        Private doIFXOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.JE_Transfer.My.MySettings.Default.JE_Transfer_WebReference_UBSWebservice
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event getBackEndStoredProcedureCallCompleted As getBackEndStoredProcedureCallCompletedEventHandler
        
        '''<remarks/>
        Public Event adaptorServiceCompleted As adaptorServiceCompletedEventHandler
        
        '''<remarks/>
        Public Event doIFXCompleted As doIFXCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("getBackEndStoredProcedureCall", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function getBackEndStoredProcedureCall(<System.Xml.Serialization.XmlElementAttribute("getBackEndStoredProcedureCall", [Namespace]:="http://www.openuri.org/")> ByVal getBackEndStoredProcedureCall1 As getBackEndStoredProcedureCall) As <System.Xml.Serialization.XmlElementAttribute("getBackEndStoredProcedureCallResponse", [Namespace]:="http://www.openuri.org/")> getBackEndStoredProcedureCallResponse
            Dim results() As Object = Me.Invoke("getBackEndStoredProcedureCall", New Object() {getBackEndStoredProcedureCall1})
            Return CType(results(0),getBackEndStoredProcedureCallResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getBackEndStoredProcedureCallAsync(ByVal getBackEndStoredProcedureCall1 As getBackEndStoredProcedureCall)
            Me.getBackEndStoredProcedureCallAsync(getBackEndStoredProcedureCall1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getBackEndStoredProcedureCallAsync(ByVal getBackEndStoredProcedureCall1 As getBackEndStoredProcedureCall, ByVal userState As Object)
            If (Me.getBackEndStoredProcedureCallOperationCompleted Is Nothing) Then
                Me.getBackEndStoredProcedureCallOperationCompleted = AddressOf Me.OngetBackEndStoredProcedureCallOperationCompleted
            End If
            Me.InvokeAsync("getBackEndStoredProcedureCall", New Object() {getBackEndStoredProcedureCall1}, Me.getBackEndStoredProcedureCallOperationCompleted, userState)
        End Sub
        
        Private Sub OngetBackEndStoredProcedureCallOperationCompleted(ByVal arg As Object)
            If (Not (Me.getBackEndStoredProcedureCallCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getBackEndStoredProcedureCallCompleted(Me, New getBackEndStoredProcedureCallCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("adaptorService", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function adaptorService(<System.Xml.Serialization.XmlElementAttribute("adaptorService", [Namespace]:="http://www.openuri.org/")> ByVal adaptorService1 As adaptorService) As <System.Xml.Serialization.XmlElementAttribute("adaptorServiceResponse", [Namespace]:="http://www.openuri.org/")> adaptorServiceResponse
            Dim results() As Object = Me.Invoke("adaptorService", New Object() {adaptorService1})
            Return CType(results(0),adaptorServiceResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub adaptorServiceAsync(ByVal adaptorService1 As adaptorService)
            Me.adaptorServiceAsync(adaptorService1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub adaptorServiceAsync(ByVal adaptorService1 As adaptorService, ByVal userState As Object)
            If (Me.adaptorServiceOperationCompleted Is Nothing) Then
                Me.adaptorServiceOperationCompleted = AddressOf Me.OnadaptorServiceOperationCompleted
            End If
            Me.InvokeAsync("adaptorService", New Object() {adaptorService1}, Me.adaptorServiceOperationCompleted, userState)
        End Sub
        
        Private Sub OnadaptorServiceOperationCompleted(ByVal arg As Object)
            If (Not (Me.adaptorServiceCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent adaptorServiceCompleted(Me, New adaptorServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("doIFX", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function doIFX(<System.Xml.Serialization.XmlElementAttribute("doIFX", [Namespace]:="http://www.openuri.org/")> ByVal doIFX1 As doIFX) As <System.Xml.Serialization.XmlElementAttribute("doIFXResponse", [Namespace]:="http://www.openuri.org/")> doIFXResponse
            Dim results() As Object = Me.Invoke("doIFX", New Object() {doIFX1})
            Return CType(results(0),doIFXResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub doIFXAsync(ByVal doIFX1 As doIFX)
            Me.doIFXAsync(doIFX1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub doIFXAsync(ByVal doIFX1 As doIFX, ByVal userState As Object)
            If (Me.doIFXOperationCompleted Is Nothing) Then
                Me.doIFXOperationCompleted = AddressOf Me.OndoIFXOperationCompleted
            End If
            Me.InvokeAsync("doIFX", New Object() {doIFX1}, Me.doIFXOperationCompleted, userState)
        End Sub
        
        Private Sub OndoIFXOperationCompleted(ByVal arg As Object)
            If (Not (Me.doIFXCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent doIFXCompleted(Me, New doIFXCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.openuri.org/")>  _
    Partial Public Class getBackEndStoredProcedureCall
        
        Private ifxMessageField As String
        
        '''<remarks/>
        Public Property ifxMessage() As String
            Get
                Return Me.ifxMessageField
            End Get
            Set
                Me.ifxMessageField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.openuri.org/")>  _
    Partial Public Class getBackEndStoredProcedureCallResponse
        
        Private getBackEndStoredProcedureCallResultField As String
        
        '''<remarks/>
        Public Property getBackEndStoredProcedureCallResult() As String
            Get
                Return Me.getBackEndStoredProcedureCallResultField
            End Get
            Set
                Me.getBackEndStoredProcedureCallResultField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.openuri.org/")>  _
    Partial Public Class adaptorService
        
        Private ifxMessageField As String
        
        '''<remarks/>
        Public Property ifxMessage() As String
            Get
                Return Me.ifxMessageField
            End Get
            Set
                Me.ifxMessageField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.openuri.org/")>  _
    Partial Public Class adaptorServiceResponse
        
        Private adaptorServiceResultField As String
        
        '''<remarks/>
        Public Property adaptorServiceResult() As String
            Get
                Return Me.adaptorServiceResultField
            End Get
            Set
                Me.adaptorServiceResultField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.openuri.org/")>  _
    Partial Public Class doIFX
        
        Private ifxMessageField As String
        
        '''<remarks/>
        Public Property ifxMessage() As String
            Get
                Return Me.ifxMessageField
            End Get
            Set
                Me.ifxMessageField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.openuri.org/")>  _
    Partial Public Class doIFXResponse
        
        Private doIFXResultField As String
        
        '''<remarks/>
        Public Property doIFXResult() As String
            Get
                Return Me.doIFXResultField
            End Get
            Set
                Me.doIFXResultField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub getBackEndStoredProcedureCallCompletedEventHandler(ByVal sender As Object, ByVal e As getBackEndStoredProcedureCallCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getBackEndStoredProcedureCallCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As getBackEndStoredProcedureCallResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),getBackEndStoredProcedureCallResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub adaptorServiceCompletedEventHandler(ByVal sender As Object, ByVal e As adaptorServiceCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class adaptorServiceCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As adaptorServiceResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),adaptorServiceResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub doIFXCompletedEventHandler(ByVal sender As Object, ByVal e As doIFXCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class doIFXCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As doIFXResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),doIFXResponse)
            End Get
        End Property
    End Class
End Namespace
